"""
This script verifies that the number of university folders in the input directory
matches the number of rows in the generated CSV output.
"""

import os  # Module to interact with the file system
import csv  # Module to handle CSV file operations
import sys  # Module used here to increase CSV field size limit


def count_subfolders(directory):
    """Count the number of subfolders in a given directory."""
    # List all items in the directory and filter only those that are directories
    subfolders = [
        f for f in os.listdir(directory)
        if os.path.isdir(os.path.join(directory, f))
    ]
    return len(subfolders)  # Return the count of valid subfolders


def count_csv_rows(csv_file):
    """Count the number of university entries in the CSV (excluding header)."""
    # Increase CSV field size limit to handle large text fields in cells
    csv.field_size_limit(sys.maxsize)  # Set the max field size to system limit

    with open(csv_file, mode='r', encoding='utf-8') as file:
        reader = csv.reader(file)
        # Count rows and subtract 1 to exclude the header
        return sum(1 for row in reader) - 1


def main():
    # Set the path to the folder containing university subfolders
    wave3_path = "/Users/helanwang/PycharmProjects/divHelan/Wave3/2021UniversityFiles"

    # Set the path to the output CSV file generated by the processing script
    csv_file = "../../outputCvs/output_wave3_content_ordered.csv"

    # Count the number of subfolders (input universities)
    subfolder_count = count_subfolders(wave3_path)
    print(f"Number of subfolders (input): {subfolder_count}")

    # Count the number of rows (output universities) in the CSV
    csv_count = count_csv_rows(csv_file)
    print(f"Number of universities in CSV (output): {csv_count}")

    # Compare input and output counts to verify they match
    if subfolder_count == csv_count:
        print("✅ **VERIFICATION PASSED**: Input and output counts match!")
    else:
        # Print details if there's a mismatch between input folders and CSV rows
        print(f"❌ **VERIFICATION FAILED**: Mismatch detected!")
        print(f"   - Input folders: {subfolder_count}")
        print(f"   - CSV entries: {csv_count}")


# Run the main function when the script is executed directly
if __name__ == "__main__":
    main()